apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: nginx
        image: sean15521304262/hello-app:v1 # 這裡先寫死 v1，等一下 Jenkins 會來自動修改它
        ports:
        - containerPort: 80
